# Generated by Django 4.2.7 on 2023-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Прошло проверку?'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Прошло проверку?'),
        ),
        migrations.AddField(
            model_name='investor',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Прошло проверку?'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Прошло проверку?'),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Прошло проверку?'),
        ),
    ]
