# Generated by Django 4.2.7 on 2023-11-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_corporation_user_alter_investfund_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='organization_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='organization_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='organization_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='public_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='public_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='public_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='contact_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='contact_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='contact_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='organization_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='organization_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='organization_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='public_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='public_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
        migrations.AddField(
            model_name='investfund',
            name='public_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
        migrations.AddField(
            model_name='investor',
            name='contact_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='investor',
            name='contact_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='investor',
            name='contact_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='investor',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='investor',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='investor',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pilotproject',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pilotproject',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pilotproject',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='pilotproject',
            name='title_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pilotproject',
            name='title_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pilotproject',
            name='title_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_en',
            field=models.TextField(null=True, verbose_name='Описание опыта'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_kk',
            field=models.TextField(null=True, verbose_name='Описание опыта'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_ru',
            field=models.TextField(null=True, verbose_name='Описание опыта'),
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='startup',
            name='contact_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='startup',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='startup',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='startup',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='startup',
            name='investors_en',
            field=models.TextField(null=True, verbose_name='Инвесторы'),
        ),
        migrations.AddField(
            model_name='startup',
            name='investors_kk',
            field=models.TextField(null=True, verbose_name='Инвесторы'),
        ),
        migrations.AddField(
            model_name='startup',
            name='investors_ru',
            field=models.TextField(null=True, verbose_name='Инвесторы'),
        ),
        migrations.AddField(
            model_name='startup',
            name='organization_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='startup',
            name='organization_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='startup',
            name='organization_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Публичное название'),
        ),
    ]
