# Generated by Django 4.2.7 on 2023-11-22 04:11

from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_corporation_is_approved_investfund_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='profile_image',
            field=models.ImageField(height_field='1200', upload_to='specialists/profiles/images/', validators=[profiles.validators.validate_image], verbose_name='Фото профиля', width_field='1200'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='resume',
            field=models.FileField(upload_to='specialists/profiles/resumes/', validators=[profiles.validators.validate_presentation], verbose_name='Резюме'),
        ),
    ]
