# Generated by Django 4.2.7 on 2023-11-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_investstage'),
        ('profiles', '0003_alter_specialist_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='stage',
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience_years',
            field=models.CharField(choices=[('Нет опыта', 'Нет опыта'), ('1-3 года', '1-3 года'), ('3-6 года', '3-6 года'), ('6+ лет', '6+ лет')], default=1, max_length=9, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='invest_stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='modules.investstage', verbose_name='Стадия инвестирования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='startup_stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='modules.startupstage', verbose_name='Стадия стартапа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.TextField(verbose_name='Описание опыта'),
        ),
    ]
