# Generated by Django 4.2.7 on 2023-12-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_bussinessmodel_name_en_bussinessmodel_name_kk_and_more'),
        ('profiles', '0003_corporation_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='country_startups', to='modules.country', verbose_name='Страна регистрации'),
        ),
    ]
