# Generated by Django 4.2.7 on 2023-11-23 08:23

from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_startup_stage_specialist_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='profile_image',
            field=models.ImageField(default=1, height_field='1200', upload_to='investors/profiles/images/', validators=[profiles.validators.validate_image], verbose_name='Фото профиля', width_field='1200'),
            preserve_default=False,
        ),
    ]
