# Generated by Django 4.2.7 on 2023-11-24 14:11

from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_investor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='logo',
            field=models.ImageField(upload_to='corporations/logos/', validators=[profiles.validators.validate_image], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='investfund',
            name='logo',
            field=models.ImageField(upload_to='invest-funds/logos/', validators=[profiles.validators.validate_image], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='profile_image',
            field=models.ImageField(upload_to='investors/profiles/images/', validators=[profiles.validators.validate_image], verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='profile_image',
            field=models.ImageField(upload_to='specialists/profiles/images/', validators=[profiles.validators.validate_image], verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(upload_to='start-up/logos/', validators=[profiles.validators.validate_image], verbose_name='Логотип'),
        ),
    ]
