# Generated by Django 4.2.7 on 2023-11-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_investstage'),
        ('profiles', '0006_alter_corporation_logo_alter_investfund_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='invest_rounds',
            field=models.ManyToManyField(related_name='corporations', to='modules.investstage', verbose_name='Раунды инвестиций'),
        ),
        migrations.AlterField(
            model_name='investfund',
            name='invest_rounds',
            field=models.ManyToManyField(related_name='invest_funds', to='modules.investstage', verbose_name='Раунды инвестиций'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='invest_rounds',
            field=models.ManyToManyField(related_name='investors', to='modules.investstage', verbose_name='Раунды инвестиций'),
        ),
    ]
