# Generated by Django 4.2.7 on 2023-11-24 15:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_appuser_phone_number_appuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+77010101000', max_length=128, region=None, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
