# Generated by Django 4.2.7 on 2023-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_type',
            field=models.CharField(choices=[('Стартап', 'Стартап'), ('Инвестор', 'Инвестор'), ('Инвестфонд', 'Инвестфонд'), ('Корпорация', 'Корпорация'), ('Специалист', 'Специалист')], default=None, max_length=10, verbose_name='Тип профиля'),
            preserve_default=False,
        ),
    ]
