# Generated by Django 4.2.7 on 2023-11-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_appuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('Стартап', 'Стартап'), ('Инвестор', 'Инвестор'), ('Инвестфонд', 'Инвестфонд'), ('Корпорация', 'Корпорация'), ('Специалист', 'Специалист')], max_length=10, null=True, verbose_name='Тип профиля'),
        ),
    ]
