# Generated by Django 4.2.7 on 2023-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appuser_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('StartUp', 'Стартап'), ('Investor', 'Инвестор'), ('InvestFund', 'Инвестфонд'), ('Corporation', 'Корпорация'), ('Specialist', 'Специалист')], max_length=11, null=True, verbose_name='Тип профиля'),
        ),
    ]
