# Generated by Django 4.2.7 on 2023-11-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appuser_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_type',
            field=models.CharField(choices=[('Стартап', 'Стартап'), ('Инвестор', 'Инвестор'), ('Инвестфонд', 'Инвестфонд'), ('Корпорация', 'Корпорация'), ('Специалист', 'Специалист')], max_length=10, null=True, verbose_name='Тип профиля'),
        ),
    ]
