# Generated by Django 4.2.7 on 2023-11-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_appuser_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('StartUp', 'StartUp'), ('Investor', 'Investor'), ('InvestFund', 'InvestFund'), ('Corporation', 'Corporation'), ('Specialist', 'Specialist')], max_length=11, null=True, verbose_name='Тип профиля'),
        ),
    ]
