# Generated by Django 4.2.7 on 2023-11-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessmodel',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='bussinessmodel',
            name='name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='bussinessmodel',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='innovationmethod',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='innovationmethod',
            name='name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='innovationmethod',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='investstage',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='investstage',
            name='name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='investstage',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sellingmodel',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sellingmodel',
            name='name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='sellingmodel',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='startupstage',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='startupstage',
            name='name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='startupstage',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_en',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_kk',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_ru',
            field=models.CharField(max_length=63, null=True, verbose_name='Название'),
        ),
    ]
