# Generated by Django 4.2.7 on 2023-11-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_investstage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestRound',
        ),
    ]
