# Generated by Django 4.2.7 on 2023-11-27 05:40

from django.db import migrations, models
import medias.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('banner', models.ImageField(upload_to='articles/', validators=[medias.validators.validate_banner], verbose_name='Баннер')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Стадия стартапа',
                'verbose_name_plural': 'Стадии стартапа',
            },
        ),
    ]
